window.PUBLICATIONS = [
  {
    title: "Structured Directional Pruning via Perturbation Orthogonal Projection",
    authors: "Xiaofeng Liu, Qing Wang, Yunfeng Shao, Yanhui Geng, Yinchuan Li",
    venue: "IEEE Transactions on Signal Processing",
    year: 2024,
    tag: "ai",
    badge: "TSP",
    featured: true,
  },
  {
    title: "Sparse Personalized Federated Learning",
    authors: "Xiaofeng Liu, Yinchuan Li, Qing Wang, Xu Zhang, Yunfeng Shao, Yanhui Geng",
    venue: "IEEE Transactions on Neural Networks and Learning Systems",
    year: 2023,
    tag: "ai",
    badge: "TNNLS",
    featured: true,
  },
  {
    title: "Neighbor Auto-Grouping Graph Neural Networks for Handover Parameter Configuration in Cellular Network",
    authors: "Mehrtash Mehrabi, Walid Masoudimansour, Yingxue Zhang, Jie Chuai, Zhitang Chen, Mark Coates, Jianye Hao, Yanhui Geng",
    venue: "AAAI 2023",
    year: 2023,
    tag: "ai",
    badge: "AAAI",
    featured: true,
  },
  {
    title: "Model-Based Offline Reinforcement Learning with Pessimism-Modulated Dynamics Belief",
    authors: "Kaiyang Guo, Yunfeng Shao, Yanhui Geng",
    venue: "NeurIPS 2022 (Oral)",
    year: 2022,
    tag: "ai",
    badge: "NeurIPS",
    featured: true,
  },
  {
    title: "Para-CFlows: C^k-universal diffeomorphism approximators as superior neural surrogates",
    authors: "Junlong Lyu, Zhitang Chen, Chang Feng, Wenjing Cun, Shengyu Zhu, Yanhui Geng, Zhijie Xu, Yongwei Chen",
    venue: "NeurIPS 2022",
    year: 2022,
    tag: "ai",
    badge: "NeurIPS",
    featured: true,
  },
  {
    title: "Node copying: A random graph model for effective graph sampling",
    authors: "Florence Regola, Soumyasundar Pal, Jianing Sun, Yingxue Zhang, Yanhui Geng, Mark Coates",
    venue: "Elsevier Signal Processing Journal",
    year: 2022,
    tag: "ai",
    badge: "Journal",
  },
  {
    title: "Sentinel: Failure Recovery in Centralized Traffic Engineering",
    authors: "Jiaqi Zheng, Hong Xu, Xiaojun Zhu, Guihai Chen, Yanhui Geng",
    venue: "IEEE/ACM Transactions on Networking",
    year: 2019,
    tag: "systems",
    badge: "ToN",
    featured: true,
  },
  {
    title: "Node-Constrained Traffic Engineering: Theory and Applications",
    authors: "George Trimponias, Yan Xiao, Xiaorui Wu, Hong Xu, Yanhui Geng",
    venue: "IEEE/ACM Transactions on Networking",
    year: 2019,
    tag: "systems",
    badge: "ToN",
  },
  {
    title: "Model-free inference of diffusion networks using RKHS embeddings",
    authors: "Shoubo Hu, Bogdan Cautis, Zhitang Chen, Laiwan Chan, Yanhui Geng, Xiuqiang He",
    venue: "Data Mining and Knowledge Discovery",
    year: 2019,
    tag: "ai",
    badge: "Journal",
  },
  {
    title: "Luopan: Sampling-based Load Balancing in Data Center Networks",
    authors: "Peng Wang, George Trimponias, Henry Xu, Yanhui Geng",
    venue: "IEEE Transactions on Parallel and Distributed Systems",
    year: 2019,
    tag: "systems",
    badge: "TPDS",
    featured: true,
  },
  {
    title: "Causal Inference and Mechanism Clustering of a Mixture of Additive Noise Models",
    authors: "Shoubo Hu, Zhitang Chen, Vahid Partovi Nia, Laiwan Chan, Yanhui Geng",
    venue: "NeurIPS 2018",
    year: 2018,
    tag: "ai",
    badge: "NeurIPS",
    featured: true,
  },
  {
    title: "Learning-based Joint Configuration for Cellular Networks",
    authors: "Xueying Gao, George Trimponias, Xiaoxiao Wang, Zhitang Chen, Yanhui Geng, Xin Liu",
    venue: "IEEE Internet of Things Journal",
    year: 2018,
    tag: "ai",
    badge: "IoT-J",
  },
  {
    title: "Faster Policy Adaptation in Environments with Exogeneity: A State Augmentation Approach",
    authors: "Zhuoshu Li, Zhitang Chen, Pascal Poupart, Sanmay Das, Yanhui Geng",
    venue: "AAMAS 2018",
    year: 2018,
    tag: "ai",
    badge: "AAMAS",
  },
  {
    title: "Seq2Img: A Sequence-to-Image Based Approach Towards IP Traffic Classification using Convolutional Neural Networks",
    authors: "Zhitang Chen, Ke He, Jian Li, Yanhui Geng",
    venue: "IEEE Big Data 2017",
    year: 2017,
    tag: "ai",
    badge: "Big Data",
  },
  {
    title: "Cellular Network Configuration via Online Learning and Joint Optimization",
    authors: "Xueying Gao, George Trimponias, Xiaoxiao Wang, Zhitang Chen, Yanhui Geng, Xin Liu",
    venue: "IEEE Big Data 2017",
    year: 2017,
    tag: "ai",
    badge: "Big Data",
  },
  {
    title: "We've Got You Covered: Failure Recovery with Backup Tunnels in Traffic Engineering",
    authors: "Jiaqi Zheng, Hong Xu, Xiaojun Zhu, Guihai Chen, Yanhui Geng",
    venue: "IEEE ICNP 2016",
    year: 2016,
    tag: "systems",
    badge: "ICNP",
  },
  {
    title: "Predicting Future Traffic using Hidden Markov Models",
    authors: "Zhitang Chen, Jiayao Wen, Yanhui Geng",
    venue: "IEEE ICNP Workshop on Machine Learning in Computer Networks (NetworkML)",
    year: 2016,
    tag: "ai",
    badge: "Workshop",
  },
  {
    title: "Online Flow Size Prediction for Improved Network Routing",
    authors: "Pascal Poupart, Zhitang Chen, Priyank Jaini, Fred Fung, Hengky Susanto, Yanhui Geng, Li Chen, Kai Chen, Hao Jin",
    venue: "IEEE ICNP Workshop on Machine Learning in Computer Networks (NetworkML)",
    year: 2016,
    tag: "ai",
    badge: "Workshop",
  },
  {
    title: "Luopan: Sampling-based Congestion-aware Load Balancing in Data Center Networks",
    authors: "Peng Wang, George Trimponias, Henry Xu, Hongyuan Liu, Yanhui Geng",
    venue: "IEEE ICNP 2016 (Poster)",
    year: 2016,
    tag: "systems",
    badge: "ICNP",
  },
  {
    title: "CODA: Towards Automatically Identifying and Scheduling Coflows in the Dark",
    authors: "Hong Zhang, Li Chen, Bairen Yi, Kai Chen, Mosharaf Chowdhury, Yanhui Geng",
    venue: "ACM SIGCOMM 2016",
    year: 2016,
    tag: "systems",
    badge: "SIGCOMM",
    featured: true,
  },
  {
    title: "Online Relative Entropy Search using Reproducing Kernel Hilbert Space Embeddings",
    authors: "Zhitang Chen, Pascal Poupart, Yanhui Geng",
    venue: "AISTATS 2016",
    year: 2016,
    tag: "ai",
    badge: "AISTATS",
  },
  {
    title: "Towards Comprehensive Traffic Forecasting in Cloud Computing: Design and Application",
    authors: "Yang Peng, Kai Chen, Guohui Wang, Wei Bai, Yangming Zhao, Hao Wang, Yanhui Geng, Zhiqiang Ma, Lin Gu",
    venue: "IEEE/ACM Transactions on Networking",
    year: 2016,
    tag: "systems",
    badge: "ToN",
  },
  {
    title: "FlowProphet: Generic and Accurate Traffic Prediction for Data-Parallel Cluster Computing",
    authors: "Hao Wang, Li Chen, Kai Chen, Ziyang Li, Yiming Zhang, Haibing Guan, Zhengwei Qi, Dongsheng Li, Yanhui Geng",
    venue: "IEEE ICDCS 2015",
    year: 2015,
    tag: "systems",
    badge: "ICDCS",
  },
  {
    title: "RAPIER: Integrating Routing and Scheduling for Coflow-aware Data Center Networks",
    authors: "Yangming Zhao, Kai Chen, Wei Bai, Minlan Yu, Chen Tian, Yanhui Geng, Yiming Zhang, Dan Li, Sheng Wang",
    venue: "IEEE INFOCOM 2015",
    year: 2015,
    tag: "systems",
    badge: "INFOCOM",
    featured: true,
  },
  {
    title: "Integration and Automation of Data Preparation and Data Mining",
    authors: "Shrikanth Narayanan, Ayush Jaiswal, Yao-Yi Chiang, Yanhui Geng, Craig A. Knoblock, Pedro Szekely",
    venue: "IEEE ICDM 2014",
    year: 2014,
    tag: "ai",
    badge: "ICDM",
  },
  {
    title: "Information-theoretic Bounds for Performance of Resource-constrained Communication Systems",
    authors: "Albert Y.S. Lam, Yanhui Geng, Victor O.K. Li",
    venue: "arXiv:1404.0142",
    year: 2014,
    tag: "systems",
    badge: "arXiv",
  },
  {
    title: "Performance Bounds of Opportunistic Scheduling in Wireless Networks",
    authors: "Yanhui Geng, Albert Y.S. Lam, Victor O.K. Li",
    venue: "IEEE GLOBECOM 2010",
    year: 2010,
    tag: "systems",
    badge: "GLOBECOM",
  },
  {
    title: "An Information-theoretic Model for Resource-constrained Systems",
    authors: "Yanhui Geng, Albert Y.S. Lam, Victor O.K. Li",
    venue: "IEEE SMC 2010",
    year: 2010,
    tag: "systems",
    badge: "SMC",
  },
  {
    title: "A Framework to Analyze Network Performance based on Information Quality",
    authors: "Yanhui Geng, Victor O.K. Li",
    venue: "IEEE ICC 2010",
    year: 2010,
    tag: "systems",
    badge: "ICC",
  },
  {
    title: "Mathematical Impact of Information Accuracy on Network Performance",
    authors: "Yanhui Geng, Victor O.K. Li",
    venue: "IEEE ICC 2010 (Best Paper Award)",
    year: 2010,
    tag: "systems",
    badge: "ICC",
    featured: true,
  },
  {
    title: "A Novel Approach to Improve the Performance of MPLS-based VPN",
    authors: "Yanhui Geng, Qiong Sun, Yuzhong Chen, Nenghai Yu",
    venue: "IEEE INES 2004",
    year: 2004,
    tag: "systems",
    badge: "INES",
  },
  {
    title: "A Mechanism Applied to Improving the Performance of MPLS VPN",
    authors: "Yanhui Geng, Qiong Sun, Nenghai Yu",
    venue: "IEEE KORUS 2004",
    year: 2004,
    tag: "systems",
    badge: "KORUS",
  },
  {
    title: "An Analysis and Comparison of L2 Link Failure Solutions in MPLS Networks",
    authors: "Yanhui Geng, Nenghai Yu, Bingqing Yang, Yuzhong Chen",
    venue: "IEEE INES 2003",
    year: 2003,
    tag: "systems",
    badge: "INES",
  },
  {
    title: "A Multipath Mechanism Applied to Traffic Engineering in MPLS Network",
    authors: "Qiong Sun, Yanhui Geng, Hui Wang, Nenghai Yu",
    venue: "IEEE INES 2004",
    year: 2004,
    tag: "systems",
    badge: "INES",
  },
  {
    title: "Reordering on Internet Based on Metric",
    authors: "Qiong Sun, Yanhui Geng, Hui Wang, Nenghai Yu",
    venue: "IEEE KORUS 2004",
    year: 2004,
    tag: "systems",
    badge: "KORUS",
  },
  {
    title: "A Mechanism to Improve the Performance of MPLS-VPN Based on Using Label Stack",
    authors: "Qiong Sun, Yanhui Geng, Nenghai Yu",
    venue: "Journal of Computer Science",
    year: 2006,
    tag: "systems",
    badge: "Journal",
  },
  {
    title: "Performance Analysis and Improvement of IEEE 802.11 WLAN",
    authors: "Yuzhong Chen, Caihong Kai, Yanhui Geng, Feng Li",
    venue: "IEEE APCC 2004",
    year: 2004,
    tag: "systems",
    badge: "APCC",
  },
  {
    title: "A Traffic Engineering Scheme for Diffserv over MPLS",
    authors: "Yuzhong Chen, Nenghai Yu, Yanhui Geng, Xuelong Li",
    venue: "IEEE ICNNSP 2003",
    year: 2003,
    tag: "systems",
    badge: "ICNNSP",
  },
  {
    title: "Combination of Traffic Engineering and Diffserv over MPLS",
    authors: "Yuzhong Chen, Nenghai Yu, Yanhui Geng, Xuelong Li",
    venue: "IEEE INES 2003",
    year: 2003,
    tag: "systems",
    badge: "INES",
  },
  {
    title: "Traffic Engineering with Constraint-based Routing in DiffServ/MPLS Network",
    authors: "Yuzhong Chen, Bingqing Yang, Rong Ren, Yanhui Geng, Nenghai Yu",
    venue: "IEEE LANMAN 2004",
    year: 2004,
    tag: "systems",
    badge: "LANMAN",
  },
];
